# Generated by Django 4.1 on 2022-08-13 03:22

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PollItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('yes', models.IntegerField(default=0)),
                ('no', models.IntegerField(default=0)),
            ],
        ),
    ]
