# Generated by Django 4.1 on 2022-08-13 13:10

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pollitem',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pollitem',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='pollitem',
            name='no',
            field=models.IntegerField(default=0, editable=False),
        ),
        migrations.AlterField(
            model_name='pollitem',
            name='yes',
            field=models.IntegerField(default=0, editable=False),
        ),
    ]
