# Generated by Django 4.1 on 2022-08-13 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_pollitem_created_at_pollitem_updated_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PollIdAndIp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ref_id', models.CharField(max_length=200)),
                ('ip', models.CharField(max_length=200)),
            ],
        ),
    ]
