# Generated by Django 4.1 on 2022-08-13 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_pollidandip'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PollIdAndIp',
            new_name='PollIdAndUserIp',
        ),
    ]
