# Generated by Django 4.1 on 2022-08-13 17:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_rename_pollidandip_pollidanduserip'),
    ]

    operations = [
        migrations.AddField(
            model_name='pollidanduserip',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pollidanduserip',
            name='ip',
            field=models.CharField(editable=False, max_length=200),
        ),
        migrations.AlterField(
            model_name='pollidanduserip',
            name='ref_id',
            field=models.CharField(editable=False, max_length=200),
        ),
    ]
